// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnuFeE3sjjOGqOl3ybpKw2tIcO1D_4GNw',
    appId: '1:440780828537:web:1620bb20e0b31967e0c9a8',
    messagingSenderId: '440780828537',
    projectId: 'system-reports-app-bfb51',
    authDomain: 'system-reports-app-bfb51.firebaseapp.com',
    storageBucket: 'system-reports-app-bfb51.appspot.com',
    measurementId: 'G-75G83WQBHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDellpXmfIBpgNG0lovWP1IJZmJY7o69ss',
    appId: '1:440780828537:android:5b69fed1957f1876e0c9a8',
    messagingSenderId: '440780828537',
    projectId: 'system-reports-app-bfb51',
    storageBucket: 'system-reports-app-bfb51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFIZOBs_8FwseR0Yq-y_3kv_xHPNbHJOQ',
    appId: '1:440780828537:ios:e754c1659447c4e0e0c9a8',
    messagingSenderId: '440780828537',
    projectId: 'system-reports-app-bfb51',
    storageBucket: 'system-reports-app-bfb51.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFIZOBs_8FwseR0Yq-y_3kv_xHPNbHJOQ',
    appId: '1:440780828537:ios:e754c1659447c4e0e0c9a8',
    messagingSenderId: '440780828537',
    projectId: 'system-reports-app-bfb51',
    storageBucket: 'system-reports-app-bfb51.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnuFeE3sjjOGqOl3ybpKw2tIcO1D_4GNw',
    appId: '1:440780828537:web:b90492a00b6e1341e0c9a8',
    messagingSenderId: '440780828537',
    projectId: 'system-reports-app-bfb51',
    authDomain: 'system-reports-app-bfb51.firebaseapp.com',
    storageBucket: 'system-reports-app-bfb51.appspot.com',
    measurementId: 'G-4WLSH8NVCK',
  );

}