// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCfTEyw05edkst2SG3BUX0pg8-rtE_RB8',
    appId: '1:950468027299:web:fa1f02f9c2799bc9cf7016',
    messagingSenderId: '950468027299',
    projectId: 'system-reports-app-d878a',
    authDomain: 'system-reports-app-d878a.firebaseapp.com',
    storageBucket: 'system-reports-app-d878a.appspot.com',
    measurementId: 'G-N0VGGN5951',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7-xb0WTxK7KaYHvmBOU95bz3s5VktGE',
    appId: '1:950468027299:android:107b1d7ed30e32a9cf7016',
    messagingSenderId: '950468027299',
    projectId: 'system-reports-app-d878a',
    storageBucket: 'system-reports-app-d878a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWDgSMCLVVAF7J7xsojpAOEvuu2dIsgY',
    appId: '1:950468027299:ios:73874ff64b7da3e3cf7016',
    messagingSenderId: '950468027299',
    projectId: 'system-reports-app-d878a',
    storageBucket: 'system-reports-app-d878a.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWDgSMCLVVAF7J7xsojpAOEvuu2dIsgY',
    appId: '1:950468027299:ios:73874ff64b7da3e3cf7016',
    messagingSenderId: '950468027299',
    projectId: 'system-reports-app-d878a',
    storageBucket: 'system-reports-app-d878a.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCfTEyw05edkst2SG3BUX0pg8-rtE_RB8',
    appId: '1:950468027299:web:83250639aacadb64cf7016',
    messagingSenderId: '950468027299',
    projectId: 'system-reports-app-d878a',
    authDomain: 'system-reports-app-d878a.firebaseapp.com',
    storageBucket: 'system-reports-app-d878a.appspot.com',
    measurementId: 'G-7QX8QFB8H4',
  );

}