// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD368B42w45MwwXe5euQbw9RlABA9qesRU',
    appId: '1:660592426653:web:542b5e01582361a6d51e74',
    messagingSenderId: '660592426653',
    projectId: 'system-reports-app',
    authDomain: 'system-reports-app.firebaseapp.com',
    storageBucket: 'system-reports-app.appspot.com',
    measurementId: 'G-V5V9X75YXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuuTPMLebekuEaYhg9ZvGrizMavSXAM8',
    appId: '1:660592426653:android:2519f0c990b4c49cd51e74',
    messagingSenderId: '660592426653',
    projectId: 'system-reports-app',
    storageBucket: 'system-reports-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBIEn4rbPlUSs4W4YUB0cnedfOCs7I_1o',
    appId: '1:660592426653:ios:bd1c45146e2118c0d51e74',
    messagingSenderId: '660592426653',
    projectId: 'system-reports-app',
    storageBucket: 'system-reports-app.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBIEn4rbPlUSs4W4YUB0cnedfOCs7I_1o',
    appId: '1:660592426653:ios:bd1c45146e2118c0d51e74',
    messagingSenderId: '660592426653',
    projectId: 'system-reports-app',
    storageBucket: 'system-reports-app.appspot.com',
    iosBundleId: 'com.example.systemReportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD368B42w45MwwXe5euQbw9RlABA9qesRU',
    appId: '1:660592426653:web:47f5bb6484980ccbd51e74',
    messagingSenderId: '660592426653',
    projectId: 'system-reports-app',
    authDomain: 'system-reports-app.firebaseapp.com',
    storageBucket: 'system-reports-app.appspot.com',
    measurementId: 'G-6K82CRJRH6',
  );
}
